[[Qt6Wayland]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a66e0fc433ce939e11e75c00b1ad53247224ed26"
libc = "musl"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "bb1d1e86decca83fdf3af518b5be99b322de53e8be7357b36fcd77193571e816"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.7.1+0/Qt6Wayland.v6.7.1.x86_64-linux-musl-cxx11.tar.gz"
