[[Qt6Wayland]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e077539325e44a02a6981f44abdfbaef3086cfb4"
libc = "glibc"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "d700ff94dc5fb6c1405f01ceccd466db95b75651d310cd7b8fb68eeafc53e88e"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.7.1+1/Qt6Wayland.v6.7.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Qt6Wayland]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "00897d317919e1ba1f8aa498f2d2b0dc0002a120"
libc = "glibc"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "9d70a6499a6a76f7ff58d2f23daf8f6c51539a540d8483d7c7baf120fb3321c3"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.7.1+1/Qt6Wayland.v6.7.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Qt6Wayland]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "36e8dcea4a5b27dd590c9438590b44c0ffe28dce"
libc = "musl"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "f8a859ac2898345db9bb2772403c4e8a9e850b3c4556731fe869a312b55edd66"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.7.1+1/Qt6Wayland.v6.7.1.aarch64-linux-musl-cxx03.tar.gz"
[[Qt6Wayland]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8839ffa46b158dc0650f42b04f6946876d9900c9"
libc = "musl"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "f64223ed8cc1eb5b48ffac1c6f38786729fbebd8e5751bb06000ab2767d74a2d"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.7.1+1/Qt6Wayland.v6.7.1.aarch64-linux-musl-cxx11.tar.gz"
[[Qt6Wayland]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "12f52faae766f52652d3ba9f7ee3e215852c6b29"
libc = "glibc"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "c9040d31c47ad430f9bbfdd56c5b80f12fda8a87bf9c53896a20660cf1261076"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.7.1+1/Qt6Wayland.v6.7.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Qt6Wayland]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af697d4a7169e9f850fca2c252423859cc7af9be"
libc = "glibc"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "38c21a4e6f3c330442e2c4b22b5b31540c7475bc484ba93e514a98b0303c1729"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.7.1+1/Qt6Wayland.v6.7.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Qt6Wayland]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9c2db59fc859a555b82fdc228246eceb4faecd87"
libc = "musl"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "2a1433bc8c21d3229715a07bba20182990752ce96f8682c531c253fa30f0a6ba"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.7.1+1/Qt6Wayland.v6.7.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Qt6Wayland]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "77e5038dba02d6e5aac895798695015963a48517"
libc = "musl"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "8eac1f1f981e2a8803dd35970c05f208216d45fde53961217d8b7f479dd73dc8"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.7.1+1/Qt6Wayland.v6.7.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Qt6Wayland]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5d4db4577cbb524adb39b47972ce2e4dc82976ce"
libc = "glibc"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "4a40a2e9017fd37501a4b8eb1f7585acd6ff2466442ef186f350aec42e25b8d3"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.7.1+1/Qt6Wayland.v6.7.1.i686-linux-gnu-cxx03.tar.gz"
[[Qt6Wayland]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4cb78c43c2acdb1f0bb31b12dba854ae0ae22a29"
libc = "glibc"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "4a96fb6c18ae856d83acf5ffc867fbf74209326339661022deed62fda3385a7c"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.7.1+1/Qt6Wayland.v6.7.1.i686-linux-gnu-cxx11.tar.gz"
[[Qt6Wayland]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "65bc72c1a0d3cc364affc64108ab1b3410e94244"
libc = "musl"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "aeba5fc75afc8a3983efc7da28f82b469261b8b48540db6080c1efe31cffb7df"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.7.1+1/Qt6Wayland.v6.7.1.i686-linux-musl-cxx03.tar.gz"
[[Qt6Wayland]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ea2ddd024b69c6422e6d9f3b6df51c54dffed1e"
libc = "musl"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "5dc3ed8d2cb97aeb7a482443629205cd105f7a348c057cb75ddf40dd6b5b9d52"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.7.1+1/Qt6Wayland.v6.7.1.i686-linux-musl-cxx11.tar.gz"
[[Qt6Wayland]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad7bc2a385383b2506ed06f5449a2916abf5f739"
libc = "glibc"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "a03f65205c84ecad2a2054a25d94abf206d7d8fd7778681ab5b772240592aed7"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.7.1+1/Qt6Wayland.v6.7.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Qt6Wayland]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "333029683623806b8e1ad1b423c4bd6e93fc4822"
libc = "glibc"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "c90abf480ac6f78e6fb2ff0f255a31840ae3222c0f510920f56945ada84e8bc8"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.7.1+1/Qt6Wayland.v6.7.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Qt6Wayland]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "05718dab53dd556ff6d55059eee14d429e7b6753"
libc = "glibc"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "a08d02ceba6111ee723f733a5d37c87431ba96805feb66c902d7a38bbc0ee388"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.7.1+1/Qt6Wayland.v6.7.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Qt6Wayland]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9773e5eff0c299268f01986828c9ce98df4c6f79"
libc = "glibc"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "75a2a5d79e79616c4ef4a066f7d8560e581cf4c1d44dfcd5fe99cdd815b8a91c"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.7.1+1/Qt6Wayland.v6.7.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Qt6Wayland]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9693a2c8d6082712d198ad2205cacc22d21f1993"
libc = "musl"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "f90681c509654084aa27c19cfa85d06fcb07cc0382c1052448a707b273b5a055"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.7.1+1/Qt6Wayland.v6.7.1.x86_64-linux-musl-cxx03.tar.gz"
[[Qt6Wayland]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "25fcf3eb28d46688dcb7a454a65e74a2b1694be3"
libc = "musl"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "4bafe18aae71bbef3e0d9f8e083675846f6a9c648c62837d9492d70fc302f3f6"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.7.1+1/Qt6Wayland.v6.7.1.x86_64-linux-musl-cxx11.tar.gz"
