[[Qt6Wayland]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f23eb35c9e943fc11bab61bc95aa7817ea561641"
libc = "musl"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "87f5913abfb544f0b4c4ac8f6713efdd9f4d25545b6eee508f8620cc66e467f4"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.8.2+0/Qt6Wayland.v6.8.2.x86_64-linux-musl-cxx11.tar.gz"
