[[Qt6Wayland]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "73fba229d84740d2ffe3c1dd38363aed577e7fb5"
libc = "musl"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "5dbed2ec018e203be1511ec2b1aa6e80d8f3af52fa9716020ff0316c67fc1089"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.10.2+0/Qt6Wayland.v6.10.2.x86_64-linux-musl-cxx11.tar.gz"
