[[Qt6Wayland]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30bdeb50f75520c10f3602cfd0c6beabcd548c48"
libc = "musl"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "3a213490e9efe850a87d810ae31777a24d8d44720da12784e2c8eeb6b8fe7e8b"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.5.2+0/Qt6Wayland.v6.5.2.x86_64-linux-musl-cxx11.tar.gz"
