[[Qt6Wayland]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "180043292424201baaa5005087ae23d8798a8392"
libc = "glibc"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "222b84f7a67c76bf5aeb390531f3c9fc0fdeef95faabe206c1d94db132ceee43"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.4.2+1/Qt6Wayland.v6.4.2.aarch64-linux-gnu-cxx03.tar.gz"
[[Qt6Wayland]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1cb504b170fc87dd284c406c85cdcdbf1c679e8"
libc = "glibc"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "eb76d2227a34b243eb294fffb63f62504f911522ad184128141074f830bf1912"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.4.2+1/Qt6Wayland.v6.4.2.aarch64-linux-gnu-cxx11.tar.gz"
[[Qt6Wayland]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c9fec469d89a6d4b04c2aedf58cddd8d7dd0b653"
libc = "musl"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "d45a834f4e65237974e86d262e453bd4430b42359bcf6a41a282317653420c21"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.4.2+1/Qt6Wayland.v6.4.2.aarch64-linux-musl-cxx03.tar.gz"
[[Qt6Wayland]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d931a869de4a0060b3a1dc61bee5a56ebb46d57"
libc = "musl"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "6b4aadbed27227f5b01beca7f73a0265efb45443123494f1a2c8924579bba6a7"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.4.2+1/Qt6Wayland.v6.4.2.aarch64-linux-musl-cxx11.tar.gz"
[[Qt6Wayland]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "259c34517d7a1bd232e4fb0ea9ee80409e957fdb"
libc = "glibc"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "74b59669e913d76e4f0c7d55209b3ba6a177f7e04b286fda850e76a875d35a39"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.4.2+1/Qt6Wayland.v6.4.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Qt6Wayland]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9287cb32b09aefaa446ff04f930411aee8339bb7"
libc = "glibc"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "9441fada6c333e1f49c38f85affb9b63ae067da8f7d0dfb1bc13fd50439fdc1a"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.4.2+1/Qt6Wayland.v6.4.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Qt6Wayland]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3f9a8b8e6fd52d9df7be4ac1b221213cf16b5d22"
libc = "musl"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "403fc4bf6bf83443eaf966921acf959a70736b156ed4be05e2408c136b81f84b"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.4.2+1/Qt6Wayland.v6.4.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Qt6Wayland]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b6b491890eba75190c3a54c46ed8fab3a38bde6"
libc = "musl"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "044c04b184b6b24a9ccf97eec8e5bae90755af781fd45ff99ab50c9b21566ba8"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.4.2+1/Qt6Wayland.v6.4.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Qt6Wayland]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "736471201fb5b911d3d7e73abe36d069aed617bf"
libc = "glibc"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "2a0b6358beb148e34d34262ac59f9947c4fb904aad27d075dd3ced81ba85b2d8"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.4.2+1/Qt6Wayland.v6.4.2.i686-linux-gnu-cxx03.tar.gz"
[[Qt6Wayland]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b68e0798315fa657ff218e7a43ff61aea352ac2a"
libc = "glibc"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "32fe5492268674b3b1a915e7e60c344c4c04154c723634c164b40f2e40e78450"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.4.2+1/Qt6Wayland.v6.4.2.i686-linux-gnu-cxx11.tar.gz"
[[Qt6Wayland]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2819045d94ab94277f28772082bfd0bf221429e5"
libc = "musl"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "09216f7776cb7d2b15e90858e8d138df168fa57f1566c4354328e19624be1a12"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.4.2+1/Qt6Wayland.v6.4.2.i686-linux-musl-cxx03.tar.gz"
[[Qt6Wayland]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a6092760896ba7e4b5c4a64629946f81bbc4584"
libc = "musl"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "1e3cea84eea68b13e1e049b6a6be2bb0010b52ecb115dc1d66c181bda65b2805"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.4.2+1/Qt6Wayland.v6.4.2.i686-linux-musl-cxx11.tar.gz"
[[Qt6Wayland]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f301956bffaaf048112d6c9d12e44b4875b5ddb3"
libc = "glibc"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "e524cac3d4cc3f750eae283707e1dc5447a23f896307f2d6b06ec85d69584751"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.4.2+1/Qt6Wayland.v6.4.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Qt6Wayland]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "76f14c3d59654c0ea21bee2d65ed2f61f9857a88"
libc = "glibc"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "2cebb34a89e006fdc8c0a3706981cc2afaca40b92391a917a19e35cd54309e25"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.4.2+1/Qt6Wayland.v6.4.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Qt6Wayland]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8dea4436b30086ba321a22b73f323644fb0ddf16"
libc = "glibc"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "77c0561b5cab2e08f6c13554e43eced849163352499425fa4f85e275dc6c1b55"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.4.2+1/Qt6Wayland.v6.4.2.x86_64-linux-gnu-cxx03.tar.gz"
[[Qt6Wayland]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d2bfcbbbe8366ca06a6b4353fd95336f5d8db87"
libc = "glibc"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "b9c8eacc389ade9b30908b5ac2c6bad783ae34bdabf142d0cf2603c0060648a9"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.4.2+1/Qt6Wayland.v6.4.2.x86_64-linux-gnu-cxx11.tar.gz"
[[Qt6Wayland]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "af2d082bbce04e22c56e3dff487e3e585855e94b"
libc = "musl"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "54690862124c478fbc7d25c83221d94ead2e306784fde7fef009d01bded25b26"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.4.2+1/Qt6Wayland.v6.4.2.x86_64-linux-musl-cxx03.tar.gz"
[[Qt6Wayland]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39cb93463f56cf8a9de1b45c0cf6ef243d7f462c"
libc = "musl"
os = "linux"

    [[Qt6Wayland.download]]
    sha256 = "02ffb4146bb085c1fa518556bac76df3e459df4676aa5ef763f552ad78c3b01b"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Wayland_jll.jl/releases/download/Qt6Wayland-v6.4.2+1/Qt6Wayland.v6.4.2.x86_64-linux-musl-cxx11.tar.gz"
